version: "3.8"
services:
  neo4j:
    build:
      context: ./neo4j/v${NEO4J_VERSION}
      args:
        VERSION: "${NEO4J_VERSION}"
        DB_USER: "${NEO4J_USER}"
        DB_PASSWORD: "${NEO4J_PASSWORD}"
        DB_AUTH: "${NEO4J_USER}/${NEO4J_PASSWORD}"
    container_name: "${NEO4J_CONTAINER_NAME}"
    ports:
      - 7474:7474 # HTTP endpoint
      - 7473:7473 # HTTPS endpoint
      - 7687:7687 # Bolt endpoint
    environment:
      - DB_HOST='localhost'
      - DB_PORT=7474
      - DB_USER=${NEO4J_USER}
      - DB_PASSWORD=${NEO4J_PASSWORD}
      - NEO4J_AUTH=${NEO4J_AUTH}
      - NEO4J_dbms_connector_https_advertised__address=localhost:7473
      - NEO4J_dbms_connector_http_advertised__address=localhost:7474
      - NEO4J_dbms_connector_bolt_advertised__address=localhost:7687
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      - NEO4JLABS_PLUGINS=["apoc"]
      - NEO4J_dbms_security_procedures_whitelist=apoc.*
      - NEO4J_uuid_enabled=true
      - NEO4J_dbms_db_timezone=SYSTEM
      - NEO4J_dbms_shell_enabled=true

    volumes:
      - ./neo4j/vol/data:/data
      - ./neo4j/vol/logs:/logs
      - ./neo4j/vol/plugins:/plugins
      - ./neo4j/vol/import:/var/lib/neo4j/import

  # api:
  #   build: ./api
  #   ports:
  #     - 4001:4001
  #   environment:
  #     - NEO4J_URI=bolt://neo4j:7687
  #     - NEO4J_USER=${NEO4J_USER}
  #     - NEO4J_PASSWORD=${NEO4J_PASSWORD}
  #     - GRAPHQL_LISTEN_PORT=4001
  #     - GRAPHQL_URI=http://localhost:4001/graphql

  #   links:
  #     - neo4j
  #   depends_on:
  #     - neo4j
